### ISSUE TITLE
No Arrow Direction of TOP_RIGHT

### ISSUE THREAD

**Issue by DanteAndroid** [MasayukiSuda/BubbleLayout#18]
I need the bubble point to a button at the top right of the screen.
![image](https://user-images.githubusercontent.com/10005563/42917249-52c8c686-8b3b-11e8-9529-d561a6ef903f.png)

**Comment by ArpitSharma2** [comment]
I am also having the same requirement. Please respond.

**Comment by ArpitSharma2** [comment]
Found  a solution for this you have to set arrow direction  "top" and after that can also set the arrow position from the xml as well as java. 

cheers !

**Comment by DanteAndroid** [comment]
@ArpitSharma2 Or you can try [https://github.com/cpiz/BubbleView](this)
