### ISSUE TITLE
Edit text inside BubbleLayout

### ISSUE THREAD

**Issue by bellus93** [MasayukiSuda/BubbleLayout#2]
BubbleLayout doesn't fit to the length of the text

**Comment by bellus93** [comment]
More: it's fits only after softkeyboard closed

**Comment by MasayukiSuda** [comment]
Call requestLayout() when softkeyboard closed.
Please try it.

**Comment by bellus93** [comment]
Bubble fits if on Edittext I add a textwatcher and on  onTextChanged call the requestLayout();

**Comment by MasayukiSuda** [comment]
Thanks.
