### ISSUE TITLE
Upgrade to androidx

### ISSUE THREAD

**Issue by bjarneheden** [MasayukiSuda/BubbleLayout#22]
It would be great if this could be updated to androidx (that dependency on com.android.support:appcompat-v7:) so we can avoid using Jetifier for this dependancy. (Jetifier makes our builds a bit slow).

**Comment by MasayukiSuda** [comment]
fix it

**Comment by bjarneheden** [comment]
Thanks!

**Comment by bjarneheden** [comment]
When I change the version to 1.2.1, it can not be found.
Looks like it is not updated in mvnrepository?

Edit: my mistake, it works as expected.
