### ISSUE TITLE
version 1.2.1 does not resolve

### ISSUE THREAD

**Issue by bjarneheden** [MasayukiSuda/BubbleLayout#24]
ERROR: Failed to resolve: com.daasuu:BubbleLayout:1.2.1

Look like the dependency is not updated in mvn repository.

**Comment by bjarneheden** [comment]
I also tried using the github link:
implementation 'com.github.MasayukiSuda:BubbleLayout:v1.2.1'
And setting it up in gradle.settings:
sourceControl {
    gitRepository("https://github.com/MasayukiSuda/BubbleLayout.git") {
        producesModule("com.github.MasayukiSuda:BubbleLayout")
    }
}

That did also not work.
Perhaps I am doing something wrong?

**Comment by MasayukiSuda** [comment]
See Read Me

**Comment by bjarneheden** [comment]
In the Read Me it says:
implementation 'com.github.MasayukiSuda:BubbleLayout:v1.2.1'

I have also set up maven { url 'https://jitpack.io' } in the build file.

Still get:
ERROR: Failed to resolve: com.github.MasayukiSuda:BubbleLayout:v1.2.1

Am I doing something wrong?

**Comment by bjarneheden** [comment]
Ah, I had only added it to repositories section and missed to also adding it in the allprojects section.
Now it works as expected!

Thank you!
