### ISSUE TITLE
How to set up the pupwindow display position The button above？

### ISSUE THREAD

**Issue by ma969070578** [MasayukiSuda/BubbleLayout#5]
popupWindow.showAtLocation(v, Gravity.NO_GRAVITY, location[0], location[1]-popupWindow.getHeight());

popupWindow.getHeight()=-2？

**Comment by pj210493** [comment]
@ma969070578 
Did you get your answer, if yes plz let me know.

**Comment by Arkuda** [comment]
@ma969070578 
@pj210493 
        popupWindow.showAtLocation(v, Gravity.NO_GRAVITY, location[0],  location[1] - v.getHeight()- 360);

where 360 - it height of popup window
